### ISSUE TITLE
Don't download/unpack/include googletest when BUILD_TESTING is set to OFF

### ISSUE THREAD

**Issue by kazuhiro** [51Degrees/common-cxx#54]
Atm, googletest is downloaded, unpacked, and included even if tests are not going to be build because of BUILD_TESTING flag set to false. Would it be possible to skip googletest related steps as well?

**Comment by Tracy51D** [comment]
@kazuhiro - Thank you for reaching out. We are aware of the issue and are working on a fix. We will update you soonest.

Thanks
Tracy

**Comment by justadreamer** [comment]
Hi @kazuhiro this has been addressed in the PR #55.  Please let us know if the patch helps, or any further improvements you would like to add.  Thank you for raising this.

**Comment by Tracy51D** [comment]
Hi @kazuhiro This issue has now been resolved. If you have any issues please feel free to re-open this ticket.

Thanks
Tracy
